### ISSUE TITLE
Unlisted attack (though a cute one)

### ISSUE THREAD

**Issue by Dawn11111111** [ronaldstoner/nostr-attacks#1]
Happy New Year reply bots, 31 Dec '23. Responsible party unknown afaik. Droves of bots replying 'happy new year(some emoji)' to kind 1s, then to eachother's  replies

**Comment by ronaldstoner** [comment]
Thanks for sharing! Is there a news article of example of that reply spam? I'm searching as well. I'd like to link a source if possible.

**Comment by Dawn11111111** [comment]
I haven't seen an article about it, but it was widely discussed by active users at the time. I'll ask around.

**Comment by ronaldstoner** [comment]
I did find some of these messages in a historical archive. I added the attack the to the list and gave you a contributing credit @Dawn11111111. If we ever find an article or source I am happy to link it in the future. Thanks!
